FROM silvesterhsu/autopilot-gpu:base

# FLANN
ENV FLANN 1.9.1
ENV FLANN_URL https://github.com/flann-lib/flann/archive/refs/tags/${FLANN}.zip

RUN cd /opt && \
    wget "${FLANN_URL}" -O flann-${FLANN}.zip && \
    unzip flann-${FLANN}.zip && \
    mkdir -p flann-${FLANN}/build && cd flann-${FLANN} && \
    touch src/cpp/empty.cpp && \
    sed -e '/add_library(flann_cpp SHARED/ s/""/empty.cpp/' \
        -e '/add_library(flann SHARED/ s/""/empty.cpp/' \
        -i src/cpp/CMakeLists.txt && \
    cd build && \
    cmake -DCMAKE_INSTALL_PREFIX=/usr/local/ \
      -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_EXAMPLES=OFF \
      -DBUILD_TESTS=OFF \
      -DBUILD_PYTHON_BINDINGS=OFF \
      -DBUILD_MATLAB_BINDINGS=OFF \
      .. && \
    make -j 15 && \
    make -j 15 install

# BOOST
ENV BOOST 1.71.0
ENV BOOST_URL https://github.com/boostorg/boost.git

RUN cd /opt && \
    git clone -b boost-${BOOST} --recursive ${BOOST_URL} && \
    cd boost && \
    ./bootstrap.sh && \
    ./b2 install --prefix=/usr/local/ --exec-prefix=/usr/local/ --with-test && \
    ./b2 install --prefix=/usr/local/ --exec-prefix=/usr/local/ link=shared runtime-link=shared threading=multi

# PCL
ENV PCL 1.11.0
ENV PCL_URL https://github.com/PointCloudLibrary/pcl/archive/refs/tags/pcl-${PCL}.zip

RUN cd /opt && \
    wget "${PCL_URL}" -O pcl-${PCL}.zip && \
    unzip pcl-${PCL}.zip && \
    mkdir -p pcl-pcl-${PCL}/build && cd pcl-pcl-${PCL}/build && \
    cmake -DCMAKE_INSTALL_PREFIX=/usr/local/ \
      -DCMAKE_BUILD_TYPE=Release \
      -DWITH_LIBUSB=FALSE \
      -DWITH_QHULL=TRUE \
      -DWITH_CUDA=FALSE \
      -DWITH_QT=FALSE \
      -DWITH_PCAP=FALSE \
      -DWITH_OPENGL=FALSE \
      -DWITH_VTK=FALSE \
      .. && \
    make -j15 && \
    make -j15 install
